import { productSearchHref } from "../data/products";

export const NEW_ARRIVALS_VIEW_ALL_HREF = "/products?sort=newest";

const product = ({
  id,
  category,
  name,
  variant,
  description,
  specifications,
  price,
  previousPrice,
  imageSrc,
  imageScale = 1,
  objectPosition = "center",
  /**
   * `contain` is the default so a product is never cropped by its stage. The
   * source renders are 2:3, 1:1 and 3:2, none of which match the media stages,
   * so `cover` scaled every image to the larger axis and cut the rest off — a
   * portrait phone lost its top and bottom, and wide renders lost their sides.
   * Safe spacing and per-category size caps live in the CSS.
   */
  mediaVariant = "contain",
  isFeatured = false,
}) => ({
  id,
  slug: id,
  category,
  name,
  variant,
  description,
  specifications,
  price,
  previousPrice,
  imageSrc,
  imageAlt: `${name}, ${variant}`,
  isNew: true,
  isFeatured,
  productUrl: productSearchHref(name),
  imageScale,
  objectPosition,
  mediaVariant,
});

export const newArrivalCollections = [
  {
    id: "all",
    labelKey: "commerce.newArrivals.tabs.all",
    featured: product({
      id: "xioma-15-pro-blue-titanium",
      category: "phones",
      name: "Xioma 15 Pro 256GB",
      variant: "Blue Titanium",
      specifications: "6.7-inch ProMotion Display • A18 Ultra Chip • 48MP Pro Camera",
      price: 1199,
      previousPrice: 1399,
      imageSrc: "/images/new-arrivals/xioma-15-pro-blue-titanium.webp",
      isFeatured: true,
    }),
    products: [
      product({
        id: "xioma-15-mint-green",
        category: "phones",
        name: "Xioma 15 128GB",
        variant: "Mint Green",
        price: 899,
        previousPrice: 999,
        imageSrc: "/images/new-arrivals/xioma-15-mint-green.webp",
      }),
      product({
        id: "novabuds-pro-white",
        category: "audio",
        name: "NovaBuds Pro",
        variant: "Active Noise Cancellation",
        price: 129,
        previousPrice: 159,
        imageSrc: "/images/new-arrivals/novabuds-pro-white.webp",
      }),
      product({
        id: "pulse-3-midnight",
        category: "wearables",
        name: "Pulse 3 Smart Watch",
        variant: "Midnight Aluminum",
        price: 199,
        previousPrice: 249,
        imageSrc: "/images/new-arrivals/pulse-3-midnight.webp",
      }),
      product({
        id: "shield-case-clear",
        category: "accessories",
        name: "Shield Case for Xioma 15 Pro",
        variant: "MagSafe Compatible",
        price: 39,
        previousPrice: 49,
        imageSrc: "/images/new-arrivals/shield-case-clear.webp",
      }),
    ],
  },
  {
    id: "phones",
    labelKey: "commerce.newArrivals.tabs.phones",
    featured: product({
      id: "xioma-16-ultra-silver",
      category: "phones",
      name: "Xioma 16 Ultra 512GB",
      variant: "Silver Frost",
      specifications: "6.9-inch LTPO Display • A19 Ultra Chip • 200MP Camera",
      price: 1399,
      previousPrice: 1499,
      imageSrc: "/images/new-arrivals/xioma-16-ultra-silver.webp",
      isFeatured: true,
    }),
    products: [
      product({
        id: "xioma-15-pro-blue",
        category: "phones",
        name: "Xioma 15 Pro 256GB",
        variant: "Deep Blue",
        price: 1149,
        previousPrice: 1249,
        imageSrc: "/images/new-arrivals/xioma-15-pro-blue.webp",
      }),
      product({
        id: "nova-x2-black",
        category: "phones",
        name: "Nova X2 256GB",
        variant: "Midnight Black",
        price: 799,
        previousPrice: 849,
        imageSrc: "/images/new-arrivals/nova-x2-black.webp",
      }),
      product({
        id: "orbit-fold-violet",
        category: "phones",
        name: "Orbit Fold 512GB",
        variant: "Cosmic Violet",
        price: 1549,
        previousPrice: 1699,
        imageSrc: "/images/new-arrivals/orbit-fold-violet.webp",
      }),
      product({
        id: "xioma-lite-coral",
        category: "phones",
        name: "Xioma Lite 128GB",
        variant: "Coral Mist",
        price: 549,
        previousPrice: 599,
        imageSrc: "/images/new-arrivals/xioma-lite-coral.webp",
      }),
    ],
  },
  {
    id: "audio",
    labelKey: "commerce.newArrivals.tabs.audio",
    featured: product({
      id: "novabuds-max-feature",
      category: "audio",
      name: "NovaBuds Max",
      variant: "Spatial Silver",
      specifications: "Adaptive Sound • Lossless Wireless • 40-hour Battery",
      price: 549,
      previousPrice: 599,
      imageSrc: "/images/new-arrivals/novabuds-max-feature.webp",
      isFeatured: true,
    }),
    products: [
      product({
        id: "novabuds-pro-white-audio",
        category: "audio",
        name: "NovaBuds Pro",
        variant: "Active Noise Cancellation",
        price: 129,
        previousPrice: 159,
        imageSrc: "/images/new-arrivals/novabuds-pro-white.webp",
      }),
      product({
        id: "soniq-studio-headphones",
        category: "audio",
        name: "Soniq Studio Headphones",
        variant: "Reference Black",
        price: 289,
        previousPrice: 329,
        imageSrc: "/images/new-arrivals/soniq-studio-headphones.webp",
      }),
      product({
        id: "pulse-speaker-mini",
        category: "audio",
        name: "Pulse Speaker Mini",
        variant: "Ocean Blue",
        price: 89,
        previousPrice: 109,
        imageSrc: "/images/new-arrivals/pulse-speaker-mini.webp",
      }),
      product({
        id: "orbit-soundbar",
        category: "audio",
        name: "Orbit Soundbar 500",
        variant: "Dolby Atmos",
        price: 399,
        previousPrice: 449,
        imageSrc: "/images/new-arrivals/orbit-soundbar.webp",
      }),
    ],
  },
  {
    id: "wearables",
    labelKey: "commerce.newArrivals.tabs.wearables",
    featured: product({
      id: "pulse-watch-ultra-feature",
      category: "wearables",
      name: "Pulse Watch Ultra",
      variant: "Titanium Midnight",
      specifications: "Dual-frequency GPS • 72-hour Battery • Depth Sensor",
      price: 699,
      previousPrice: 749,
      imageSrc: "/images/new-arrivals/pulse-watch-ultra-feature.webp",
      isFeatured: true,
    }),
    products: [
      product({
        id: "pulse-3-midnight-wearables",
        category: "wearables",
        name: "Pulse 3 Smart Watch",
        variant: "Midnight Aluminum",
        price: 199,
        previousPrice: 249,
        imageSrc: "/images/new-arrivals/pulse-3-midnight.webp",
      }),
      product({
        id: "orbit-fit-band",
        category: "wearables",
        name: "Orbit Fit Band",
        variant: "Graphite",
        price: 79,
        previousPrice: 99,
        imageSrc: "/images/new-arrivals/orbit-fit-band.webp",
      }),
      product({
        id: "nova-watch-classic",
        category: "wearables",
        name: "Nova Watch Classic",
        variant: "Brushed Steel",
        price: 279,
        previousPrice: 319,
        imageSrc: "/images/new-arrivals/nova-watch-classic.webp",
      }),
      product({
        id: "luma-smart-ring",
        category: "wearables",
        name: "Luma Smart Ring",
        variant: "Titanium Silver",
        price: 249,
        previousPrice: 279,
        imageSrc: "/images/new-arrivals/luma-smart-ring.webp",
      }),
    ],
  },
  {
    id: "accessories",
    labelKey: "commerce.newArrivals.tabs.accessories",
    featured: product({
      id: "shield-accessory-bundle",
      category: "accessories",
      name: "Shield Essential Bundle",
      variant: "For Xioma 15 Pro",
      specifications: "Clear Case • 45W Charger • Magnetic Stand • Power Bank",
      price: 189,
      previousPrice: 229,
      imageSrc: "/images/new-arrivals/shield-accessory-bundle.webp",
      isFeatured: true,
    }),
    products: [
      product({
        id: "shield-case-clear-accessories",
        category: "accessories",
        name: "Shield Case for Xioma 15 Pro",
        variant: "MagSafe Compatible",
        price: 39,
        previousPrice: 49,
        imageSrc: "/images/new-arrivals/shield-case-clear.webp",
      }),
      product({
        id: "nova-fast-charger",
        category: "accessories",
        name: "Nova Fast Charger",
        variant: "45W USB-C GaN",
        price: 49,
        previousPrice: 59,
        imageSrc: "/images/new-arrivals/nova-fast-charger.webp",
      }),
      product({
        id: "orbit-magnetic-stand",
        category: "accessories",
        name: "Orbit Magnetic Stand",
        variant: "Adjustable Aluminum",
        price: 69,
        previousPrice: 79,
        imageSrc: "/images/new-arrivals/orbit-magnetic-stand.webp",
      }),
      product({
        id: "pulse-power-bank",
        category: "accessories",
        name: "Pulse Power Bank",
        variant: "10,000mAh Magnetic",
        price: 79,
        previousPrice: 99,
        imageSrc: "/images/new-arrivals/pulse-power-bank.webp",
      }),
    ],
  },
];

export const newArrivalImageManifest = Array.from(
  new Set(
    newArrivalCollections.flatMap((collection) => [
      collection.featured.imageSrc,
      ...collection.products.map((item) => item.imageSrc),
    ])
  )
);
