import { productSearchHref } from "../data/products";

export const TODAYS_PICKS_VIEW_ALL_HREF = "/products?sort=recommended";

const pick = ({
  id,
  categoryKey,
  recommendationKey,
  name,
  variantKey,
  descriptionKey,
  reasonKey,
  featureKeys,
  price,
  previousPrice,
  imageSrc,
  imageScale = 1,
  objectPosition = "center",
  mediaVariant = "contain",
  accent = "blue",
}) => ({
  id,
  slug: id,
  categoryKey,
  recommendationKey,
  name,
  variantKey,
  descriptionKey,
  reasonKey,
  featureKeys,
  price,
  previousPrice,
  imageSrc,
  productUrl: productSearchHref(name),
  imageScale,
  objectPosition,
  mediaVariant,
  accent,
});

/**
 * Editorial metadata is intentionally kept separate from the core catalogue.
 * The products page is currently static, so each pick links to the existing
 * search route instead of pretending a product-detail or cart API exists.
 */
export const todaysPicks = [
  pick({
    id: "featured-flagship-phone",
    categoryKey: "commerce.todaysPicks.categories.phone",
    recommendationKey: "commerce.todaysPicks.labels.editorsPick",
    name: "Xioma 14 Pro 256GB",
    variantKey: "commerce.todaysPicks.products.phone.variant",
    descriptionKey: "commerce.todaysPicks.products.phone.description",
    reasonKey: "commerce.todaysPicks.products.phone.reason",
    featureKeys: [
      "commerce.todaysPicks.features.camera",
      "commerce.todaysPicks.features.battery",
      "commerce.todaysPicks.features.fiveG",
    ],
    price: 1049,
    previousPrice: 1199,
    imageSrc: "/images/todays-picks/featured-flagship-phone.webp",
    imageScale: 1.06,
    objectPosition: "52% 52%",
    accent: "blue",
  }),
  pick({
    id: "premium-earbuds",
    categoryKey: "commerce.todaysPicks.categories.audio",
    recommendationKey: "commerce.todaysPicks.labels.bestValue",
    name: "NovaBuds Pro",
    variantKey: "commerce.todaysPicks.products.earbuds.variant",
    descriptionKey: "commerce.todaysPicks.products.earbuds.description",
    reasonKey: "commerce.todaysPicks.products.earbuds.reason",
    featureKeys: [
      "commerce.todaysPicks.features.noiseCancellation",
      "commerce.todaysPicks.features.spatialAudio",
      "commerce.todaysPicks.features.fastCharge",
    ],
    price: 129,
    previousPrice: 159,
    imageSrc: "/images/todays-picks/novabuds-pro.webp",
    imageScale: 1.08,
    accent: "cyan",
  }),
  pick({
    id: "smartwatch-midnight",
    categoryKey: "commerce.todaysPicks.categories.wearable",
    recommendationKey: "commerce.todaysPicks.labels.trendingToday",
    name: "Pulse 3 Smart Watch",
    variantKey: "commerce.todaysPicks.products.watch.variant",
    descriptionKey: "commerce.todaysPicks.products.watch.description",
    reasonKey: "commerce.todaysPicks.products.watch.reason",
    featureKeys: [
      "commerce.todaysPicks.features.healthTracking",
      "commerce.todaysPicks.features.gps",
      "commerce.todaysPicks.features.waterResistance",
    ],
    price: 199,
    previousPrice: 249,
    imageSrc: "/images/todays-picks/pulse-3-smart-watch.webp",
    imageScale: 1.03,
    accent: "violet",
  }),
  pick({
    id: "tablet-creative",
    categoryKey: "commerce.todaysPicks.categories.tablet",
    recommendationKey: "commerce.todaysPicks.labels.staffChoice",
    name: "Xioma Pad 6 128GB",
    variantKey: "commerce.todaysPicks.products.tablet.variant",
    descriptionKey: "commerce.todaysPicks.products.tablet.description",
    reasonKey: "commerce.todaysPicks.products.tablet.reason",
    featureKeys: [
      "commerce.todaysPicks.features.display",
      "commerce.todaysPicks.features.pencilReady",
      "commerce.todaysPicks.features.lightweight",
    ],
    price: 329,
    previousPrice: 399,
    imageSrc: "/images/todays-picks/xioma-pad-6-128gb.webp",
    imageScale: 1.04,
    accent: "indigo",
  }),
  pick({
    id: "magnetic-accessory",
    categoryKey: "commerce.todaysPicks.categories.accessory",
    recommendationKey: "commerce.todaysPicks.labels.worthDiscovering",
    name: "Orbit Magnetic Stand",
    variantKey: "commerce.todaysPicks.products.accessory.variant",
    descriptionKey: "commerce.todaysPicks.products.accessory.description",
    reasonKey: "commerce.todaysPicks.products.accessory.reason",
    featureKeys: [
      "commerce.todaysPicks.features.magneticMount",
      "commerce.todaysPicks.features.adjustable",
      "commerce.todaysPicks.features.aluminum",
    ],
    price: 69,
    previousPrice: 79,
    imageSrc: "/images/todays-picks/orbit-magnetic-stand.webp",
    imageScale: 1.08,
    accent: "emerald",
  }),
];

export const todaysPicksImageManifest = todaysPicks.map((item) => item.imageSrc);
